//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace companion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("companion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:local=&quot;clr-namespace:companion.Resources&quot;&gt;
        ///
        ///    &lt;SolidColorBrush  x:Key=&quot;DarkBlue&quot;&gt;#0c4b5d&lt;/SolidColorBrush&gt;
        ///    &lt;SolidColorBrush  x:Key=&quot;LightBlue&quot;&gt;#cde7f3&lt;/SolidColorBrush&gt;
        ///    &lt;SolidColorBrush  x:Key=&quot;LightGray&quot;&gt;#979797&lt;/SolidColorBrush&gt;
        ///
        ///&lt;/ResourceDictionary&gt;.
        /// </summary>
        internal static string ColorsDictionary {
            get {
                return ResourceManager.GetString("ColorsDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:local=&quot;clr-namespace:companion.Resources&quot;&gt;
        ///
        ///    &lt;Style x:Key=&quot;DemoCompanionWindow&quot; TargetType=&quot;{x:Type Window}&quot;&gt;
        ///        &lt;Setter Property=&quot;WindowStyle&quot; Value=&quot;None&quot;/&gt;
        ///        &lt;Setter Property=&quot;AllowsTransparency&quot; Value=&quot;True&quot;/&gt;
        ///        &lt;Setter Property=&quot;ResizeMode&quot; Value=&quot;NoResize&quot;/&gt;
        ///        &lt;Setter Property=&quot;Backgr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StylesDictionary {
            get {
                return ResourceManager.GetString("StylesDictionary", resourceCulture);
            }
        }
    }
}
